Issue160/client set info
redis/NRedisStack pull request #180
Opened 2023-08-31 12:55 UTC by shacharPash

2023-09-21 13:21 UTC, slorello89 requested changes

2023-09-21 13:28 UTC, slorello89 commented on src/NRedisStack/Auxiliary.cs
> +                _setInfo = false;
also, your tests don't work in conjunction because `_setInfo` is static and never being reverted :)

2023-09-21 14:18 UTC, shacharPash commented on src/NRedisStack/Auxiliary.cs
> +            XDocument csprojDocument = GetCsprojDocument();
for some reason when I pulled from the binary I got 0.9.0.0 as a version instead of 0.9.0.
any idea why?

2023-09-21 14:21 UTC, slorello89 commented on src/NRedisStack/Auxiliary.cs
> +            XDocument csprojDocument = GetCsprojDocument();
Major.Minor.Build.Revision - classic Msft versioning

2023-09-21 14:22 UTC, slorello89 commented on src/NRedisStack/Auxiliary.cs
> +            XDocument csprojDocument = GetCsprojDocument();
see: https://learn.microsoft.com/en-us/dotnet/standard/assembly/versioning#assembly-version-number

2023-10-19 08:10 UTC, chayim approved these changes

2023-10-19 10:05 UTC, merged