adding JSON commands
redis/NRedisStack pull request #29
Opened 2022-09-01 20:31 UTC by slorello89

2022-09-04 08:00 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    /// <param name="stop">The ending index within the array. Exclusive</param>
Missing line break here

2022-09-04 08:00 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    /// <summary>
Missing line break here

2022-09-04 08:07 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ArrayLength(RedisKey key, string? path = null);
The command name should be exactly as it is called in the documentation to avoid confusion.
Should ce called "ArrLen"

2022-09-04 08:08 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ArrayAppend(RedisKey key, string? path, params object[] values);
The command name should be exactly as it is called in the documentation to avoid confusion.
Should be callded "ArrAppend".

2022-09-04 08:09 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ArrayIndex(RedisKey key, string? path, object value, long? start = null, long? stop = null);
The command name should be exactly as it is called in the documentation to avoid confusion.
Should be callded "ArrIndex".

2022-09-04 08:09 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ArrayInsert(RedisKey key, string path, long index, params object[] values);
The command name should be exactly as it is called in the documentation to avoid confusion.
Should be callded "ArrInsert".

2022-09-04 08:11 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public RedisResult[] ArrayPop(RedisKey key, string? path = null, long? index = null);
Should ce called "ArrPop"

2022-09-04 08:11 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ArrayTrim(RedisKey key, string path, long start, long stop);
Should ce called "ArrTrim"

2022-09-04 08:16 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public IEnumerable<HashSet<string>> ObjectKeys(RedisKey key, string? path = null);
Should ce called "ObjKeys"

2022-09-04 08:17 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] ObjectLength(RedisKey key, string? path = null);
Should ce called "ObjLen"

2022-09-04 08:17 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] StringAppend(RedisKey key, string? path, string value);
Should ce called "StrAppend"

2022-09-04 08:18 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public long?[] StringLength(RedisKey key, string? path = null);
Should ce called "StrLen"

2022-09-04 12:34 UTC, shacharPash commented on src/NRedisStack/Json/JsonCommands.cs
> +    }
Why didn't you returned "res.ToArray();" instead all this if's

2022-09-04 12:37 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +
missing JSON.DEBUG and JSON.DEBUG MEMORY commands

2022-09-04 12:40 UTC, shacharPash commented on src/NRedisStack/Json/JsonCommands.cs
> +    public RedisResult Get(RedisKey key, RedisValue? indent = null, RedisValue? newLine = null, RedisValue? space = null, RedisValue? path = null)
Missed option of multiplate paths here

2022-09-04 12:41 UTC, shacharPash commented on src/NRedisStack/Json/IJsonCommands.cs
> +    public RedisResult Get(RedisKey key, RedisValue? indent = null, RedisValue? newLine = null, RedisValue? space = null, RedisValue? path = null);
Missed option of multiplate paths here

2022-09-04 13:11 UTC, shacharPash commented on src/NRedisStack/Json/JsonCommands.cs
> +        }
Why not write it in ResponseParser?

2022-09-04 13:22 UTC, shacharPash commented on src/NRedisStack/Json/JsonCommands.cs
> +            result = _db.Execute(JSON.TOGGLE, key, "$");
Why not: result = _db.Execute(JSON.TOGGLE, key)?

2022-09-04 13:45 UTC, shacharPash requested changes
Thank you!
couple things,
1. Need to add Async version for the function & tests.
2. I wrote some comments about things that I didnt understand, please have a look.

2022-09-06 18:55 UTC, slorello89 commented on src/NRedisStack/Json/JsonCommands.cs
> +        }
moved

2022-09-06 18:56 UTC, slorello89 commented
Added async commands, added multi-path get, added debug memory command, other cleanup

2022-09-07 13:14 UTC, shacharPash approved these changes
Great work :+1:

2022-09-07 13:14 UTC, merged