Change InfoResult::Attributes Returned Value to Array of Arrays
redis/NRedisStack pull request #295
Opened 2024-05-01 08:56 UTC by shacharPash

Fixes #291

2024-05-06 08:37 UTC, dvora-h approved these changes

2024-05-06 09:38 UTC, uglide requested changes

2024-05-06 09:38 UTC, uglide commented on src/NRedisStack/Search/DataTypes/InfoResult.cs
> +    // private Dictionary<string, RedisResult>[]? GetRedisResultDictionaryArray(string key)
Why not remove it instead?

2024-05-06 09:38 UTC, uglide commented on tests/NRedisStack.Tests/Search/SearchTests.cs
> +        Schema sc = new Schema().AddTextField("title", 1.0, sortable: true);
I think we need to test both cases with sortable and not sortable text fields to ensure it's still usable for not sortable.

2024-08-07 08:18 UTC, uglide approved these changes
LGTM

2024-08-07 08:19 UTC, merged